/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel_management_system;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class LoginForm extends javax.swing.JFrame {

    ConnectionToDB CTB = new ConnectionToDB();
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
         Dimension dim= Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txt_Name = new javax.swing.JTextField();
        Btn_SignIn = new javax.swing.JLabel();
        Btn_CNA = new javax.swing.JLabel();
        Psd_Pass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(999, 664));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 274, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, 33));

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGIN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 181, -1));

        Txt_Name.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jPanel1.add(Txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 271, 187, 33));

        Btn_SignIn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        Btn_SignIn.setText("Sign In");
        Btn_SignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_SignInMouseClicked(evt);
            }
        });
        jPanel1.add(Btn_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 408, -1, -1));

        Btn_CNA.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        Btn_CNA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn_CNA.setText("Create New Account ");
        Btn_CNA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_CNAMouseClicked(evt);
            }
        });
        jPanel1.add(Btn_CNA, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 447, 142, 33));

        Psd_Pass.setPreferredSize(new java.awt.Dimension(187, 33));
        jPanel1.add(Psd_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LB.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CNAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_CNAMouseClicked
        try {
            RegistrationForm RF = new RegistrationForm();
            this.setVisible(false);
            RF.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Btn_CNAMouseClicked

    private void Btn_SignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_SignInMouseClicked

        try {
            CTB.EstablishConnection();
            String UN = Txt_Name.getText();
            String UP = new String(Psd_Pass.getPassword());

            Login AL = new Login();
            boolean B = AL.AdminLogin(UN, UP);
            boolean A = AL.StudentLogin(UN, UP);
            if (B) {
                JOptionPane.showMessageDialog(null, " Successfully Loggedin ");
                ControlPanelAdmin CPA = new ControlPanelAdmin();
                this.setVisible(false);
                CPA.setVisible(true);

                String Name, Ad, Co;
                int Id;

                ConnectionToDB Con1 = new ConnectionToDB();
                Connection Conn = Con1.EstablishConnection();
                PreparedStatement Psmt = null;
                ResultSet Res = null;

                try {

                    DefaultTableModel model = (DefaultTableModel) CPA.AlloteesTable.getModel();
                    model.setRowCount(0);

                    String str3 = "Select * from Room_tbl";
                    Psmt = Conn.prepareStatement(str3);
                    Res = Psmt.executeQuery();

                    while (Res.next()) {
                        Id = Res.getInt("ID");
                        UN = Res.getString("AlloteeName");
                        Ad = Res.getString("Address");
                        Co = Res.getString("Contact");

                        model.addRow(new Object[]{Id, UN, Ad, Co});
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            } else if (A) {
                JOptionPane.showMessageDialog(null, " Successfully Loggedin ");
                ControlPanelAdmin CPA = new ControlPanelAdmin();
                ControlPanelAllotee CPS = new ControlPanelAllotee();
                this.setVisible(false);
                CPS.setVisible(true);

                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                Date date = new Date();
                CPS.Txt_DnT.setText(formatter.format(date));

            } else {
                JOptionPane.showMessageDialog(null, " Incorrect User Name & Password ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_Btn_SignInMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btn_CNA;
    private javax.swing.JLabel Btn_SignIn;
    private javax.swing.JPasswordField Psd_Pass;
    private javax.swing.JTextField Txt_Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
